### ISSUE TITLE
Tool Module Missing

### ISSUE THREAD

**Issue by ghost** [Veil-Framework/Veil#143]
## Veil version
3.1.4

## OS Used - all info (architecture, linux flavor, etc)
4.13.0-kali1-amd64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github. Reinstalled from https://github.com/Veil-Framework/Veil just before posting here. 

## Did you run the setup script?
Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
cd Veil
./Veil.py

Traceback (most recent call last):
  File "./Veil.py", line 87, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/root/Veil/lib/common/orchestra.py", line 23, in __init__
    self.load_tools(cli_stuff)
  File "/root/Veil/lib/common/orchestra.py", line 65, in load_tools
    name.replace("/", ".").rstrip('.py'), name)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "Tools/Evasion/Tool.py", line 16, in <module>
    from Tools.Evasion.evasion_common import shellcode_help
  File "/root/Veil/Tools/Evasion/evasion_common/shellcode_help.py", line 30, in <module>
    import Tool as Ordnance_Import
ModuleNotFoundError: No module named 'Tool'

## Expected behavior
Veil to start

## Any additional info you want to tell me

Checked out the closed issue here: https://github.com/Veil-Framework/Veil/issues/109 but I'm not sure if the solution is the same. If so, what do I need to do to make sure there is a mirror for downloads? 

I also think I have the same issue as here: https://github.com/Veil-Framework/Veil/issues/113. But they never replied so it was closed.

**Comment by ChrisTruncer** [comment]
Did you at any point install this via apt?

I can't seem to recreate this issue. When I install via cloning the repo, everything loads. If you have any ways to reproduce this, I'm happy to look into it.

**Comment by ghost** [comment]
Hmmm...I never have installed from apt. In fact, I didn't even know apt had Veil until reading through the closed issues. 

Maybe I need to make sure Kali is updated all the way and try cloning from the repo again? When I run the setup script, I nuke the old veil/wine settings. Would it be better to delete all the veil files myself and then do a clean clone from the repo and run the setup script?

**Comment by ghost** [comment]
I just deleted all the Veil files, recloned from the repo, ran the setup script, and got the same error. Would I need to delete the Wine environment in root/config? The nuke should have done that, but maybe not?

**Comment by ghost** [comment]
Ok, I ran apt-get update, apt-get upgrade, and apt-get dist-upgrade so everything has been updated. I also ran apt autoremove to clear everything out. Then I rebooted, deleted and recloned the repo files and ran the setup script. Same error. I'm not sure what else to do. 

Do you want me to post the code from any of the lines mentioned in the error?

**Comment by ChrisTruncer** [comment]
I’ll do another test, I’ll pull down latest Kali and install again. Give me a few hours and I’ll post my results

**Comment by nmvega** [comment]
Hi Chris and friends ...

I'm coming from the data streaming and analytics side of the world, so pardon the newbie question. I was about to install Veil via the provided git instructions when I saw this thread mention that it was available in the apt repositories.

I was wondering why this tool wasn't already installed as part of Kali Linux distribution natively (where apt install wouldn't be needed). Fedora, for example, omits certain software items for various reasons (licenses, agreements, instability, etc), and was wondering if Kali approaches things similarly. It's just an ecosystem kind of question. :)

Thank you.

**Comment by ChrisTruncer** [comment]
Hi,

I still can't replicate this issue. I just grabbed the latest Kali, installed it in my VM, and installed Veil. The tool starts without throwing an error.

@nmvega - for future issues, it would be best to start your own vs. popping into another one.
I don't control apt packages, it's the maintainers of the different distros that do. So it is up to them if they want it installed by default.

**Comment by nmvega** [comment]
@ChrisTruncer You're right about starting another issue (my bad). Will do, and thank you.

**Comment by ghost** [comment]
Ok. TheKali Iso version I am using on my VM was downloaded back in August. I figured everything would work right if I updated using apt-get. The only thing I can think of doing would be to do what you did and download the latest Kali, reinstall it to the VM, and then getting Veil. I'll do that today and get back later today or tomorrow.

**Comment by ghost** [comment]
Ok, I got it to work now. I downloaded the latest version of the Kali vbox (since I'm using virtualbox) iso from https://www.offensive-security.com/kali-linux-vmware-virtualbox-image-download/. 

Then I installed the OS and cloned and installed Veil from here. Everything ran fine! I think it was just the version of Kali I was running. It may have been old or perhaps I wasn't using the vbox image.

**Comment by gpaynter-eig** [comment]
I was having this exact same issue trying to install Veil to a Kali Linux VirtualBox VM.

I'm following a tutorial that instructed to use apt-get to install -- It appears the tutorial was published prior to the release of Veil 3. After googling and finding this bug report, I removed the package and tried to clone the git repo. I kept encountering the same error which was driving me nuts. I spent some time troubleshooting and here is what I discovered:

It appears that apt installs a wrapper script to /usr/bin/veil:
```bash
#!/bin/bash

cd /usr/share/Veil && ./Veil.py "$@"
```

So, it looks like apt-get remove did not fully uninstall veil, since I saw all of the files still under /usr/share/Veil.

My solution was to `rm -rf /usr/share/Veil` and then edit the wrapper to point to where I cloned repo.

```bash
#!/bin/bash

cd ~/git/Veil && ./Veil.py "$@"
```

I believe this is why downloading a new Kali VM image worked for OP.

Hoping my solution is helpful for anyone else encountering this issue. While not a bug with Veil per se, it definitely tripped me up when trying to install Veil as recommended by the documentation. Cheers!

**Comment by graypay** [comment]
I was having this exact same issue trying to install Veil to a Kali Linux VirtualBox VM.

I'm following a tutorial that instructed to use apt-get to install -- It appears the tutorial was published prior to the release of Veil 3. After googling and finding this bug report, I removed the package and tried to clone the git repo. I kept encountering the same error which was driving me nuts. I spent some time troubleshooting and here is what I discovered:

It appears that apt installs a wrapper script to /usr/bin/veil:
```bash
#!/bin/bash

cd /usr/share/Veil && ./Veil.py "$@"
```

So, it looks like apt-get remove did not fully uninstall veil, since I saw all of the files still under `/usr/share/Veil`.

My solution was to `rm -rf /usr/share/Veil` and then edit the wrapper to point to where I cloned repo.
```bash
#!/bin/bash

cd ~/git/Veil && ./Veil.py "$@"
```

I believe this is why downloading a new Kali VM image worked for OP.

Hoping my solution is helpful for anyone else encountering this issue. While not a bug with Veil per se, it definitely tripped me up when trying to do a clean install Veil as recommended by the documentation. Cheers!

**Comment by ghost** [comment]
Thanks for figuring out what was happening. That's really good to know. I've linked back to this in other forums I posted this issue in.
