### ISSUE TITLE
cant start Veil

### ISSUE THREAD

**Issue by Exotic-Algorithms** [Veil-Framework/Veil#219]
## sudo ./setup.sh

##error was as following:       [!] ERROR #2-3: Can't find the Metasploit Framework (/opt/metasploit-framework/embedded/framework/).   Run: /usr/share/veil/config/setup.sh --force --silent

Please note that metasploit is installed under /usr/share/metasploit-framework. This might be the issue but i dont know how to change where veil looks for metasploit.

**Comment by ChrisTruncer** [comment]
Hi there,
I don't manage how Parrot maintainers package Veil into a package, so I can't speak to that. I would recommend you install Veil by cloning the git repo, and running the setup script. This should also show the location of the settings file (/etc/veil/settings.py)

**Comment by samhaxr** [comment]
I have solved this issue in Parrot OS. Metasploit-framework is by default installed in /usr/share/metasploit-framework. Follow the commands in order to run Veil in parrot OS.

**Veil Installation**
apt -y install veil
/usr/share/veil/config/setup.sh --force --silent

**Fixing error in parrot OS**
#mkdir /opt/metasploit-framework/
#mkdir /opt/metasploit-framework/embedded
#mkdir /opt/metasploit-framework/embedded/framework
#cd /usr/share/metasploit-framework
#cp -r * /opt/metasploit-framework/embedded/framework
#cd /usr/share/veil/config/
./setup.sh

It will work 100%

**Comment by ghost** [comment]
@samhaxr Excellent guide man ! it's really helped me to fix it up . Thanks

**Comment by itsAj3** [comment]
consider making a sym link of the dir "**metasploit-framework**" found in " **/usr/share/metasploit-framework**" in the "**/opt/metasploit-framework/embedded/framework**" instead of copying the whole directory.

**Comment by karanbalajirs** [comment]
@samhaxr it worked buddy. Thanks.
