### ISSUE TITLE
question

### ISSUE THREAD

**Issue by usama7628674** [Veil-Framework/Veil#222]
I used option 2 (ordnance) then selected payload rev_tcp and set badchars \x00\x0a\x0d and generated the shellcode.My question is the generated shellcode 32 bit or 64bit?If it's 32 bit then how can I generate 64 bit shellcode?

**Comment by ChrisTruncer** [comment]
The shellcode is 32 bit. At the moment, there isn't a method to generate x64 shellcode in Veil-Ordnance, but it would be a good idea to get that added in.

If it's something you'd also be interested in adding, then I'd also be happy to review a pull request for it.

Otherwise this will be something I will look into once I get the time and availability. Thanks for the suggestion.
