### ISSUE TITLE
Is it possible to install it on VPS - without X server?

### ISSUE THREAD

**Issue by poopaapoopaa** [Veil-Framework/Veil#229]
## Veil version
3.1.6

## OS Used - all info (architecture, linux flavor, etc)
VPS - Debian 8 - with ssh access

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from git

## Did you run the setup script?
Yes. 
./config/setup.sh --force --silent

## Pastebin link to error you are encountering (include console actions you took prior to error)
Various errors, including:

>>Application tried to create a window, but no driver could be loaded.
>>Make sure that your X server is running and that $DISPLAY is set correctly.

and:

>>[ERROR] There was issues installing the following:
>>Failed to install (Wine) Ruby.exe... Exit code: 1
>>Failed to run (wine) Ruby OCRA.. Exit code: 49

## Expected behavior
Completion of installation with no errors.

## Any additional info you want to tell me

Obviously I have no X Server on the VPS. Is it possible to install that way? Or any partial version?

**Comment by ChrisTruncer** [comment]
Yes, it is possible to install without an active X server. Please read the readme for directions on how to install from github, not from apt.

**Comment by poopaapoopaa** [comment]
As I specified in my post, I installed from git. Not from apt. I followed the directions in the readme and got the above errors.
Will appreciate your assistance. Thank you.

**Comment by ChrisTruncer** [comment]
I just tested, and can confirm the exact issues you are running into. It did not work on my system, and as to why, I can't speak to that. This isn't going to be my first priority, I would recommend performing X Server forwarding and running an X server locally (if needed for headless operation on Debian). At this point, I don't know if this is for all servers headlessly, or just Debian.

For the time being, my recommendation is to run X server locally, but thank you for reporting this. If I get the opportunity, this will be something I review sooner rather than later.

**Comment by jeffmcjunkin** [comment]
I've been able to work around this as follows:
```
apt install xvfb
Xvfb :0 -screen 0 1024x768x16 &
export DISPLAY=:0.0
# Install Veil as normal afterwards
```
