### ISSUE TITLE
Create a quick access from terminal

### ISSUE THREAD

**Issue by leiferdjango** [Veil-Framework/Veil#248]
this is a preaty basic one, sorry about my ignorance, that i will is to is create a shorcut from the original path > /pentest/Veil to access from the terminal just typing Veil + ENTER

**Comment by ChrisTruncer** [comment]
To be honest, I would personally assume that if people are using Veil on Linux, then they know how to run Veil from the command line via any method that they want to. Thanks for the suggestion, but I don't plan on adding this in. Rather than doing this by default, I would want to have the user do this themselves.

**Comment by leiferdjango** [comment]
@ChrisTruncer why you have to be rude?? I know how to use Veil pretty well. YOU ASSUME I HAVE TO KNOW EVERYTHING? if can't help, do not prive me to get help from others.

**Comment by ChrisTruncer** [comment]
You are reading too much into my previous message. That wasn't directed at you, but at Veil users in general. If someone is using a program to generate anti-virus evading executables, I feel it is a reasonable assumption to make that they know how to run Veil either from the script itself or any other method.

Additionally, I don't want this behavior by default for Veil as I think it might be intrusive. If someone wants to symlink Veil.py, or do anything else, they are free to do so.
