### ISSUE TITLE
shellcode encryption

### ISSUE THREAD

**Issue by RealHarshThakur** [Veil-Framework/Veil#271]
## Veil version
Veil 3

This isn't really an issue but a suggestion for a feature to add in. Can you consider to encrypt the shellcodes generated? This feature is supported by msf5 but it would really nice to see it built in with veil.

**Comment by ChrisTruncer** [comment]
Is this something that isn't just supported with msf? You already have the option to pass additional command line parameters into msfvenom, so would that not work?

**Comment by RealHarshThakur** [comment]
msfvenom(msf4),  doesn't support shellcode encryption like RC4 etc and since msf5(supports shellcode encryption) is in beta stage for a while and Ordance doesn't have much encrypters built in, I was hoping for more encrypters to be added in the veil framework.

**Comment by ChrisTruncer** [comment]
For the time being, I don't plan on adding beta/still in development shellcode generation within Veil. However, if you have msf5 installed, I'm always open to someone testing the integration with it and letting me know how it works.

Ordnance doesn't have any encrypters, but I'm always open to a pull request with them :)

Only other thing to note is that encrypted shellcode **might** need different memory permissions, so that would need to be reviewed as well.
