### ISSUE TITLE
options not setting correctly

### ISSUE THREAD

**Issue by jmccaughey07** [Veil-Framework/Veil#278]
whenever I use the set command to set an option that is case sensitive it always sets it in lowercase even while using uppercase letters. It's also causing the payload not to generate because the option isn't set correctly

**Comment by ChrisTruncer** [comment]
Can you give an example please?

**Comment by jmccaughey07** [comment]
when set the option USE_PYHERION Y and look back at the options the Y is set to lowercase so that it looks like this 

USE_PYHERION    	y       	Use the pyherion encrypter

**Comment by ChrisTruncer** [comment]
This shouldn't cause the payload to not generate, but I do see where the code is forcing the input to be set to all lowercase. I could see at some point case-sensitivity might matter, so this should be an easy fix to do.

**Comment by PresidentBarnum** [comment]
Howdy, 

I used Kali's quick install & got this...

E: Unable to locate package monodoc-browser
E: Unable to locate package monodevelop
 [ERROR] Failed to install dependencies...Exit code: 100

I've uninstalled & reinstalled, a couple of times, as per Veil's instructions ('rm -rf /root/.config/wine/veil') and re-run 
'root/Veil-Evasion/setup/setup.sh -c' but same error appears. 

Very grateful for any help with this.

Sincerely...PresidenBarnum

**Comment by ChrisTruncer** [comment]
President - please create your own Github issue with the requested info vs jumping into unrelated issues.

Please also search for an answer first


________________________________

**Comment by jmccaughey07** [comment]
It's only when I change the no to yes on pyherion that I get the error.

**Comment by ChrisTruncer** [comment]
I looked into the code, even if you set the value of Pyherion to Y, and the code sets it to "y", pyherion is still used. I personally validated this in the code on a new system, so this has no impact on if the payload is generated or not.

I also checked the other checks and their corresponding code. They do set strings to lowercase where appropriate, but also because when they dynamically pull that information from the system, before a comparison is made, the value is also lowercased. Therefore there shouldn't be any bug here and I'll close the issue.

If you can show me a way to create a crash, I am happy to look into it.
