### ISSUE TITLE
[!] ERROR: Unable to create output file

### ISSUE THREAD

**Issue by j4b4zao** [Veil-Framework/Veil#314]
please help 

wine: /var/lib/veil/wine is not owned by you
===============================================================================
                                   Veil-Evasion
===============================================================================
      [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
===============================================================================

 [!] ERROR: Unable to create output file.
 [*] Source code written to: /var/lib/veil/output/source/testet.py
 [*] Metasploit Resource file written to: /var/lib/veil/output/handlers/testet.

**Comment by ChrisTruncer** [comment]
The error message is telling you exactly what the problem is "The directory is not owned by you". Please change ownership of the directory so you can write there.

Also, we ask all the questions when creating a github issue so we can better help troubleshoot a problem. Please help us out by answering the questions the next time you make an issue.

Thanks!

**Comment by j4b4zao** [comment]
Thank you

**Comment by AshravJ** [comment]
How to  change ownership of the directory
