### ISSUE TITLE
I cant create exe file with pyinstaller

### ISSUE THREAD

**Issue by AdamPach** [Veil-Framework/Veil#410]
## Veil version
3.1

## OS Used - all info (architecture, linux flavor, etc)

kali linux 2020
## How did you install Veil? (Apt, Clone from Github, etc.)

apt
## Did you run the setup script?

yes
## Pastebin link to error you are encountering (include console actions you took prior to error)
i

## Expected behavior
Create exe file

## Any additional info you want to tell me
Hi can you help with my problem, i dont know where is a problem. I cant create exe from python payloads when i set pyinstaler. Can you help me?

**Comment by ChrisTruncer** [comment]
Can you please try on a clean Kali system and don't install via apt? We don't control those packages, so I can't confirm that it sets it up int he exact same way that we do via git. I'll close this ticket for now, but feel free to respond with more information on a clean, up to date version of Kali.

Additionally, please provide all the information requested from you when creating a github issue so that we can use that to help troubleshoot the problem.
