### ISSUE TITLE
Veil can't find the Wine profile for Ruby v1.8.7

### ISSUE THREAD

**Issue by halyhellcord** [Veil-Framework/Veil#459]
- Veil version: Last Version

- OS Used: Linux Kali 2021.4 x86_64

- Veil Installation: Via APT

- Pastebin: https://pastebin.com/uVLYa4qv

- Expected Behavior: I expect Veil to run on my machine.

Additionally, I ran the '--force --silent' installation before, it didn't work. I also tried nuking the Wine folder, which had also no result.

Any help is appreciated, thanks!
~haly

**Comment by Idlefase** [comment]
Hello there,

There are many issue tickets talking about this kind of problem. Yet the makers of veil evasion seem not to care neither does someone had a solution.

The best advice right now is either to clone the script and modify it, but since this is not adviced in kali its best to open a ticket in their bug tracker. 

Ny excuses for the lack of straightforward advice and solutions.

Hope this somewhat helped in your Journey. 

Happy hacking and stay safe from the pandemic .

-Vilematrix

**Comment by halyhellcord** [comment]
Thanks for the response!

I will try to poke around and see what I can do. 

Thanks again and have a good day!
~haly

**Comment by Idlefase** [comment]
Hey there @DeltaHalycone 

I want to come back upon my statement because i Just found out that a handy framework i personally use also support veil evasion.

Its called ptf and it is hosted here on github and from a big trusted source.

It will build and install all tools. And uses a metasploit like menu.

Altrough its highly adviced against it by offensive security you can give it a shot.

Peform these steps if you want

- apt update
-make sure git,python3 and python3-pip are installed
- git clone the repo and cd into it.
- install the libs trough a requirements.txt
- cd into the config folder and modify the config file.
- cd .. and do sudo ./ptf

It will detect debian, checks for active internet conn. And try to update itself trough git.

Then you can do 

- search veil.
- use 《module》
-installl.

It will highly likely add metasploit trough the nightly rapid 7 repo so thats a thing to look out for when using kali. 

I hope this will help. 

- [☆] Succes

**Comment by halyhellcord** [comment]
I installed the PTF, and it's totally awesome. However, installation of VF had the same errors. I think I will just look for different tool. PTF is really helpful, thanks for advice!


Thanks a lot, I really appreciate the help!

**Comment by Idlefase** [comment]
You are more than welcome. Im glad i could help.

**Comment by halyhellcord** [comment]
Also, speaking of alternatives, I found an awesome tool called Phantom Evasion. Works just fine, though you'll need to edit  some files there. Encryption at its finest :D
Veil also seems very convenient, but sadly, it doesn't seem to work.

Thanks for your help with all of this and happy hacking!

**Comment by Idlefase** [comment]
Thanks, it will be usefull in my Journey.❤
