### ISSUE TITLE
Can't install on BackBox

### ISSUE THREAD

**Issue by MarieUwU-nerd** [Veil-Framework/Veil#56]
## Veil version
Veil (Setup Script) | [Updated]: 2017-01-24

OS : 
Distributor ID:	Ubuntu (BackBox)
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Comment by ChrisTruncer** [comment]
This didn't give me any of the information that I need to help debug this, the information that's already pre-populated when you create a github issue.

Please fill out the required information otherwise I can't really help.

Also, to be honest, I'm more supporting the latest version of Ubuntu, not 14.04, packages change and I don't have the time to completely maintain backwards compatibility forever.
